# Generated by Django 3.0.8 on 2020-08-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='scrap_function',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
