# Generated by Django 3.0.8 on 2020-08-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20200802_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='url',
            new_name='URL',
        ),
        migrations.AlterField(
            model_name='info',
            name='Image Source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
