# Generated by Django 3.0.8 on 2020-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20200802_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Image Source',
        ),
        migrations.RemoveField(
            model_name='info',
            name='URL',
        ),
        migrations.AddField(
            model_name='info',
            name='img_src',
            field=models.URLField(blank=True, null=True, verbose_name='Image Source'),
        ),
        migrations.AddField(
            model_name='info',
            name='url',
            field=models.URLField(default='https://google.com', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
