# Generated by Django 3.0.8 on 2020-08-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_auto_20200802_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
    ]
