# Generated by Django 3.0.8 on 2020-08-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_auto_20200803_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='img_src',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image Source'),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
    ]
