# Generated by Django 3.0.8 on 2020-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_remove_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='en_name',
            field=models.CharField(default='chlorochine', max_length=50),
            preserve_default=False,
        ),
    ]
